### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by RedBoardDev** [shellcatt/tuya-smartlife-api-node#1]
Hello,

I don't know if it's an oversight or a bug, but session.json doesn't exist and so I get an error on launch.
So I've added this file. But when I try to run something, I get an authentication error:

`&> node cli list
Error: Could not init Smart Life session. TuyaSmartLifeException [Error]: you cannot auth exceed once in 180 seconds
    at SmartLifeSession.getAccessToken (file:///tmp/xw5qomT3/tuya-smartlife-api-node/TuyaSmartLifeClient.mjs:75:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TuyaSmartLifeClient.init (file:///tmp/xw5qomT3/tuya-smartlife-api-node/TuyaSmartLifeClient.mjs:160:5)
    at async init (file:///tmp/xw5qomT3/tuya-smartlife-api-node/cli.js:53:13)
    at async Command.<anonymous> (file:///tmp/xw5qomT3/tuya-smartlife-api-node/cli.js:106:3)
s) Device  `

**Comment by shellcatt** [comment]
This is a legit error - in case of successful login, another login of the same user is not permitted within 180 seconds. 
This limitation comes from the Tuya portal itself, so just wait for a bit and try again. 

Please check the latest version (`0.7.4`), where I've added interactive login. 
Now credentials are saved in user's $HOME, as well as the session JSON, so no need to do much than just have an account with SmartLife.

**Comment by RedBoardDev** [comment]
Thanks you ! I'll try it when I'll have more time and give you a feedback
